List all warnings instead of returning when the first problem is found, and improve debug message.

diff --git a/internal/resources-validation.yml b/internal/resources-validation.yml
--- a/internal/resources-validation.yml
+++ b/internal/resources-validation.yml
@@ -22,15 +22,24 @@ jobs:
         sudo apt install -y pngcrush
     - displayName: 'Process PNG files using pngcrush'
       script: |
+        # Initialize error counter and error messages
+        errors=0
+        error_messages=""    
         # Print the full paths of PNG files
-        find . -type f -name "*.png" -print
-        # Run pngcrush command on PNG files and check for Profile issues
+        find . -type f -name "*.png" -print 
+        # Run pngcrush command on PNG files and check for errors
         for file in $(find . -type f -name "*.png"); do
           output=$(pngcrush -n -q "$file" 2>&1)
           echo "$output"
-          if [[ "$output" == *"pngcrush: iCCP:"* ]]; then
-            echo "Warning processing file $file"
-            exit 1
+          if [[ "$output" == *"pngcrush: iCCP"* ]]; then
+              errors=$((errors + 1))
+              error_messages+="$output\n"
           fi
         done
+        # If there were any errors, print custom message and error messages
+        if [ $errors -gt 0 ]; then
+          echo -e "\nThe following PNG files have profile errors. Consider using an optimizing PNG image tool like mogrify to fix or strip the incorrect profiles:\n"
+          echo -e "$error_messages"
+          exit $(($errors > 254 ? 254 : $errors))
+        fi
       workingDirectory: $(Build.SourcesDirectory)/resources
